[build-system]
requires = ["setuptools>=61.0", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "aftab"
dynamic = ["version"]
authors = [
  { name="Taha Shieenavaz", email="tahashieenavaz@gmail.com" },
]
description = "A highly configurable implementation of Aftab framework, benchmarking different convolutional neural networks and the effects of advanced value functions on parallelized deep Q-networks."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = ["numpy", "envpool", "baloot", "torch", "hl_gauss_pytorch"]
keywords = ["reinforcement learning", "dqn", "aftab", "drl", "pqn", "deep reinforcement learning", "cnn"]
license = { file = "LICENSE" }

[project.urls]
Homepage = "https://github.com/tahashieenavaz/aftab"
Repository = "https://github.com/tahashieenavaz/aftab"
Documentation = "https://github.com/tahashieenavaz/aftab#readme"

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests*", "docs*", "figures*", "mermaid*", "scripts*"]

[tool.setuptools.package-data]
aftab = ["*.md", "*.txt", "*.png"]

[tool.setuptools_scm]